### ISSUE TITLE
Mismatching entries in autoUpdater.xml

### ISSUE THREAD

**Issue by TimurKelman** [jecowa/soundsensepack#2]
Some files in `autoUpdater.xml` are missing and others probably have wrong sha1 or size.

Using fresh Soundsense, delete it's packs folder; change autoUpdateURLs in configuration.xml to this pack
```xml
<autoUpdateURLs>
	<item path="https://raw.githubusercontent.com/jecowa/soundsensepack/master"/>
</autoUpdateURLs>
```
and run "Pack update".
After everything is downloaded, restart and run "Pack update" again.

It will look like this.

```
Changed: autoUpdater.xml
Changed: battle.xml
Changed: breath.xml
Changed: gore.xml
Changed: hitevents.xml
Changed: status.xml
Changed: strikes.xml
New: 85791__sandyrb__NATIVE_FLUTE_FIGURE_02.wav
New: customHost.xml
New: Drop Metal Thing-SoundBible.com-401640954.ogg
New: playlist.m3u
New: playlist.pls
New: readme.txt
New: sample.xml
New: Sword Strike And Clash-SoundBible.com-1345262316.mp3
```

"Changed" are files with wrong parameters (I guess), "New" are missing files.

**Comment by jecowa** [comment]
Thank you. I think it's fixed now.

**Comment by TimurKelman** [comment]
Something is causing an `Error: java.lang.NullPointerException`, maybe the missing `sha1`-value in `<file name="autoUpdater.xml" size="115624"/>`.

**Comment by TimurKelman** [comment]
Adding `sha1="" ` seems to help.

**Comment by jecowa** [comment]
Thanks for the tip. I didn't know how to place the sha1 value of that file in the file without changing the sha1 of the file

**Comment by TimurKelman** [comment]
the last release is almost there: only `emotion.xml` has wrong sha1 and size and is updated every time.

**Comment by jecowa** [comment]
Thank you. Hopefully it's good now.

**Comment by TimurKelman** [comment]
yep, only `autoUpdater.xml` is touched on update now, which is normal because of the empty checksum.
