### ISSUE TITLE
[Ubuntu 20.04] Soundsense not working properly.

### ISSUE THREAD

**Issue by Bl4ckh34d** [jecowa/soundsensepack#3]
OS: Ubuntu 20.04 6-Bit
Starterpack: PyLNP 0.14a
DFHack: 0.47.05-r2

Hi, Soundsense doesn't do anything when I start it. I can't use any of the Buttons or Subbuttons in it (Settings, Load, Options).
When clicking the buttons, they open up submenu buttons, but clicking those has no effect. Nothing happens and while in Game, no sounds are being played besides of the standard sound track from DF.
 ![grafik](https://user-images.githubusercontent.com/63246613/129817035-71b5872d-1bd6-41df-88fe-5ed0d0093d37.png)

EDIT: Soundsense-rs is not your SoundSense? In that case, ignore this issue.

**Comment by xboxnoob** [comment]
i think you confused
you have to download the soundpack seperately then load it via the load context menu and navigate to the place you extracted the soundpack

**Comment by xboxnoob** [comment]
also this isnt the github for soundsense-rs

**Comment by jecowa** [comment]
It's at https://github.com/prixt/soundsense-rs/ if you still need.
